
  import { undefinedTheImportanceOfLettingGo,IsItOkayToOrgasmIfYouHaveAPornAddiction,WhatIsNeverFapDeluxe,WhatToDoWhenYoureIntenselyCravingPorn,WhatItFeelsLikeNotToBeAddictedToPorn,TheEasiestWayToNotTakeOurEmotionsPersonally,TheBiggestJudgementPornAddictsMake,WhyYouShouldNeverDependOnYourEmotions,TheUltimateAimOfNeverFapDeluxePractices,TheEasiestWayToIdentifyAJudgement,YourPornAddictionIsNotWhoYouAre,TheNeverFapStateOfMind,CreatingYourFirstNeverFapSchedule,YouAlwaysHaveTimeForYourMentalHealth,TheFivePrinciplesOfNeverFapAsTheyRelateToMyLife,EverythingIsAChoice,TheImportanceOfMeditationForPornAddiction,PayingTheNeverFapMaintenanceTax,WhatMakesNeverFapSoDifferent,WhyamIAPornAddict,TheOneRuleOfNeverFap,TheFiveFundamentalPrinciplesOfNeverFap,MyPersonalPornRecoveryJourney,IntroductionToTheNeverFapDeluxeGuide, } from '../content/api/articles.ts
  const ArticlesScreens = new Map();

  export const THEIMPORTANCEOFLETTINGGO_SCREEN = 'navigation.TheImportanceOfLettingGoScreen';
export const ISITOKAYTOORGASMIFYOUHAVEAPORNADDICTION_SCREEN = 'navigation.IsItOkayToOrgasmIfYouHaveAPornAddictionScreen';
export const WHATISNEVERFAPDELUXE_SCREEN = 'navigation.WhatIsNeverFapDeluxeScreen';
export const WHATTODOWHENYOUREINTENSELYCRAVINGPORN_SCREEN = 'navigation.WhatToDoWhenYoureIntenselyCravingPornScreen';
export const WHATITFEELSLIKENOTTOBEADDICTEDTOPORN_SCREEN = 'navigation.WhatItFeelsLikeNotToBeAddictedToPornScreen';
export const THEEASIESTWAYTONOTTAKEOUREMOTIONSPERSONALLY_SCREEN = 'navigation.TheEasiestWayToNotTakeOurEmotionsPersonallyScreen';
export const THEBIGGESTJUDGEMENTPORNADDICTSMAKE_SCREEN = 'navigation.TheBiggestJudgementPornAddictsMakeScreen';
export const WHYYOUSHOULDNEVERDEPENDONYOUREMOTIONS_SCREEN = 'navigation.WhyYouShouldNeverDependOnYourEmotionsScreen';
export const THEULTIMATEAIMOFNEVERFAPDELUXEPRACTICES_SCREEN = 'navigation.TheUltimateAimOfNeverFapDeluxePracticesScreen';
export const THEEASIESTWAYTOIDENTIFYAJUDGEMENT_SCREEN = 'navigation.TheEasiestWayToIdentifyAJudgementScreen';
export const YOURPORNADDICTIONISNOTWHOYOUARE_SCREEN = 'navigation.YourPornAddictionIsNotWhoYouAreScreen';
export const THENEVERFAPSTATEOFMIND_SCREEN = 'navigation.TheNeverFapStateOfMindScreen';
export const CREATINGYOURFIRSTNEVERFAPSCHEDULE_SCREEN = 'navigation.CreatingYourFirstNeverFapScheduleScreen';
export const YOUALWAYSHAVETIMEFORYOURMENTALHEALTH_SCREEN = 'navigation.YouAlwaysHaveTimeForYourMentalHealthScreen';
export const THEFIVEPRINCIPLESOFNEVERFAPASTHEYRELATETOMYLIFE_SCREEN = 'navigation.TheFivePrinciplesOfNeverFapAsTheyRelateToMyLifeScreen';
export const EVERYTHINGISACHOICE_SCREEN = 'navigation.EverythingIsAChoiceScreen';
export const THEIMPORTANCEOFMEDITATIONFORPORNADDICTION_SCREEN = 'navigation.TheImportanceOfMeditationForPornAddictionScreen';
export const PAYINGTHENEVERFAPMAINTENANCETAX_SCREEN = 'navigation.PayingTheNeverFapMaintenanceTaxScreen';
export const WHATMAKESNEVERFAPSODIFFERENT_SCREEN = 'navigation.WhatMakesNeverFapSoDifferentScreen';
export const WHYAMIAPORNADDICT_SCREEN = 'navigation.WhyamIAPornAddictScreen';
export const THEONERULEOFNEVERFAP_SCREEN = 'navigation.TheOneRuleOfNeverFapScreen';
export const THEFIVEFUNDAMENTALPRINCIPLESOFNEVERFAP_SCREEN = 'navigation.TheFiveFundamentalPrinciplesOfNeverFapScreen';
export const MYPERSONALPORNRECOVERYJOURNEY_SCREEN = 'navigation.MyPersonalPornRecoveryJourneyScreen';
export const INTRODUCTIONTOTHENEVERFAPDELUXEGUIDE_SCREEN = 'navigation.IntroductionToTheNeverFapDeluxeGuideScreen';

  ArticlesScreens.set(THEIMPORTANCEOFLETTINGGO_SCREEN, TheImportanceOfLettingGo);
ArticlesScreens.set(ISITOKAYTOORGASMIFYOUHAVEAPORNADDICTION_SCREEN, IsItOkayToOrgasmIfYouHaveAPornAddiction);
ArticlesScreens.set(WHATISNEVERFAPDELUXE_SCREEN, WhatIsNeverFapDeluxe);
ArticlesScreens.set(WHATTODOWHENYOUREINTENSELYCRAVINGPORN_SCREEN, WhatToDoWhenYoureIntenselyCravingPorn);
ArticlesScreens.set(WHATITFEELSLIKENOTTOBEADDICTEDTOPORN_SCREEN, WhatItFeelsLikeNotToBeAddictedToPorn);
ArticlesScreens.set(THEEASIESTWAYTONOTTAKEOUREMOTIONSPERSONALLY_SCREEN, TheEasiestWayToNotTakeOurEmotionsPersonally);
ArticlesScreens.set(THEBIGGESTJUDGEMENTPORNADDICTSMAKE_SCREEN, TheBiggestJudgementPornAddictsMake);
ArticlesScreens.set(WHYYOUSHOULDNEVERDEPENDONYOUREMOTIONS_SCREEN, WhyYouShouldNeverDependOnYourEmotions);
ArticlesScreens.set(THEULTIMATEAIMOFNEVERFAPDELUXEPRACTICES_SCREEN, TheUltimateAimOfNeverFapDeluxePractices);
ArticlesScreens.set(THEEASIESTWAYTOIDENTIFYAJUDGEMENT_SCREEN, TheEasiestWayToIdentifyAJudgement);
ArticlesScreens.set(YOURPORNADDICTIONISNOTWHOYOUARE_SCREEN, YourPornAddictionIsNotWhoYouAre);
ArticlesScreens.set(THENEVERFAPSTATEOFMIND_SCREEN, TheNeverFapStateOfMind);
ArticlesScreens.set(CREATINGYOURFIRSTNEVERFAPSCHEDULE_SCREEN, CreatingYourFirstNeverFapSchedule);
ArticlesScreens.set(YOUALWAYSHAVETIMEFORYOURMENTALHEALTH_SCREEN, YouAlwaysHaveTimeForYourMentalHealth);
ArticlesScreens.set(THEFIVEPRINCIPLESOFNEVERFAPASTHEYRELATETOMYLIFE_SCREEN, TheFivePrinciplesOfNeverFapAsTheyRelateToMyLife);
ArticlesScreens.set(EVERYTHINGISACHOICE_SCREEN, EverythingIsAChoice);
ArticlesScreens.set(THEIMPORTANCEOFMEDITATIONFORPORNADDICTION_SCREEN, TheImportanceOfMeditationForPornAddiction);
ArticlesScreens.set(PAYINGTHENEVERFAPMAINTENANCETAX_SCREEN, PayingTheNeverFapMaintenanceTax);
ArticlesScreens.set(WHATMAKESNEVERFAPSODIFFERENT_SCREEN, WhatMakesNeverFapSoDifferent);
ArticlesScreens.set(WHYAMIAPORNADDICT_SCREEN, WhyamIAPornAddict);
ArticlesScreens.set(THEONERULEOFNEVERFAP_SCREEN, TheOneRuleOfNeverFap);
ArticlesScreens.set(THEFIVEFUNDAMENTALPRINCIPLESOFNEVERFAP_SCREEN, TheFiveFundamentalPrinciplesOfNeverFap);
ArticlesScreens.set(MYPERSONALPORNRECOVERYJOURNEY_SCREEN, MyPersonalPornRecoveryJourney);
ArticlesScreens.set(INTRODUCTIONTOTHENEVERFAPDELUXEGUIDE_SCREEN, IntroductionToTheNeverFapDeluxeGuide);

  export default ArticlesScreens;

  